#!/bin/sh

if [ "$BSPWM_RESET_PADDING" == "true" ]; then
  bspc config top_padding 0
  bspc config bottom_padding 0
  bspc config left_padding 0
  bspc config right_padding 0
fi

bspc config border_width 16
#bspc config border_width 0
bspc config window_gap 24
#bspc config window_gap 0
bspc config normal_border_color "#333333"
bspc config active_border_color "#DDDDDD"
bspc config focused_border_color "#99AA99"
bspc config focused_border_color "#181818"
bspc config presel_feedback_color "#DDDD00"

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc rule -a Gimp desktop='^4' follow=on
bspc rule -a Spotify desktop='^5' follow=on
bspc rule -a firefox desktop='^9' follow=on
bspc rule -a KeePassXC desktop='^10' follow=on

bspc monitor any --reset-desktops I II III IV V VI VII VIII IX X

test -e "$HOME/.wallpaper" && feh --bg-fill -xZ "$HOME/.wallpaper" &

[ -e "$PANEL_FIFO" ] && bspc subscribe report > "$PANEL_FIFO" &
pgrep -x panel > /dev/null || panel &
