#!/bin/sh

bspc monitor --reset-desktops I II III IV V VI VII VIII IX X

if [ "$BSPWM_RESET_PADDING" == "true" ]; then
  bspc config top_padding 0
  bspc config bottom_padding 0
  bspc config left_padding 0
  bspc config right_padding 0
fi

bspc config border_width 16
bspc config window_gap 24
bspc config normal_border_color "#333333"
bspc config active_border_color "#DDDDDD"
bspc config focused_border_color "#99AA99"
bspc config focused_border_color "#181818"
bspc config presel_feedback_color "#DDDD00"

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc rule -a spotify desktop='^5'
bspc rule -a firefox desktop='^9'
bspc rule -a keepassxc desktop='^10'

test -e "$HOME/.wallpaper" && feh --bg-fill "$HOME/.wallpaper" &

[ -e "$PANEL_FIFO" ] && bspc subscribe report > "$PANEL_FIFO" &
pgrep -x panel > /dev/null || panel &
