#! /bin/sh

bspc monitor --reset-desktops I II III IV V VI VII VIII IX X

bspc config border_width 2
bspc config window_gap 12
bspc config normal_border_color "#333333"
bspc config active_border_color "#DDDDDD"
bspc config focused_border_color "#00DD00"
bspc config presel_feedback_color "#DDDD00"

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc rule -a firefox desktop='^9'
bspc rule -a keepassxc desktop='^10'

test -e "$HOME/.wallpaper" && feh --bg-fill "$HOME/.wallpaper" &

[ -e "$PANEL_FIFO" ] && bspc subscribe report > "$PANEL_FIFO" &
pgrep -x panel > /dev/null || panel &
