#! /bin/sh

if xdo id -a "$PANEL_WM_NAME" > /dev/null; then
  printf "%s\n" "The panel is already running." >&2
  exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

stdbuf -oL $HOME/scripts/temperature.sh subscribe | sed -u 's/^/TEMP/' > "$PANEL_FIFO" &
stdbuf -oL $HOME/scripts/cpu.sh subscribe | sed -u 's/^/CPU/' > "$PANEL_FIFO" &
stdbuf -oL $HOME/scripts/memory.sh subscribe | sed -u 's/^/MEM/' > "$PANEL_FIFO" &
stdbuf -oL $HOME/scripts/volume.sh subscribe-status | sed -u 's/^/VOL/' > "$PANEL_FIFO" &
xtitle -sf 'T%s\n' > "$PANEL_FIFO" &
clock -sf 'CLK%A %d %B %H:%M' > "$PANEL_FIFO" &
bspc subscribe report > "$PANEL_FIFO" &

. panel_colors

panel_bar < "$PANEL_FIFO" | lemonbar -b -a 32 -u 2 -n "$PANEL_WM_NAME" -g x$PANEL_HEIGHT -f "$PANEL_FONT" -F "$COLOR_DEFAULT_FG" -B "$COLOR_DEFAULT_BG" | sh &

wid=$(xdo id -m -a "$PANEL_WM_NAME")
xdo above -t "$(xdo id -N Bspwm -n root | sort | head -n 1)" "$wid"

wait
