#!/bin/ansible-playbook

# playbook NOT READY
# please have a look to base16/build-and-update.sh

- hosts:
    - current
  tasks:
    - name: Install base16-shell to ~/.config/base16-shell
      ansible.builtin.git:
        repo: 'https://github.com/chriskempson/base16-shell.git'
        dest: '{{ user_home }}/.config/base16-shell'
        version: master
    - name: Install base16-shell rc script for zsh
      ansible.builtin.lineinfile:
        create: true
        path: '{{ user_home }}/.zshrc'
        line: |
          # Base16 Shell
          export BASE16_THEMES_PATH="$HOME/.config/base16-themes"
          BASE16_SHELL="$HOME/.config/base16-shell/"
          [ -n "$PS1" ] && \
              [ -s "$BASE16_SHELL/profile_helper.sh" ] && \
                  source "$BASE16_SHELL/profile_helper.sh"
          # end Base16 Shell
    - name: Install base16-shell rc script for bash
      ansible.builtin.lineinfile:
        create: true
        path: '{{ user_home }}/.bashrc'
        line: |
          # Base16 Shell
          export BASE16_THEMES_PATH="$HOME/.config/base16-themes"
          BASE16_SHELL="$HOME/.config/base16-shell/"
          [ -n "$PS1" ] && \
              [ -s "$BASE16_SHELL/profile_helper.sh" ] && \
                  source "$BASE16_SHELL/profile_helper.sh"
          # end Base16 Shell
    - name: Install python3-pip
      become: '{{ become_for_package }}'
      ansible.builtin.package:
        name:
          - python3-pip
        state: latest
    - name: Install pybase16-builder
      ansible.builtin.pip:
        name: "pybase16-builder"
        state: "present"
    - name: Create pybase16-builder directory
      ansible.builtin.file:
        dest: "{{ user_home }}/.config/pybase16-builder"
        state: directory
