#!/bin/ansible-playbook

- hosts:
    - current
  vars:
    install_language_servers: true
  tasks:
    - name: Install neovim
      become: '{{ become_for_package }}'
      ansible.builtin.package:
        name:
          - neovim
          - cmake
          - ripgrep
        state: latest
    - name: Install language servers
      become: '{{ become_for_package }}'
      ansible.builtin.package:
        name:
          - bash-language-server
          - lua-language-server
          - elixir-ls
          - tailwindcss-language-server
          - clangd
          - arduino-cli
          - arduino-language-server
        state: latest
      when: install_language_servers
