#!/bin/ansible-playbook

- hosts:
    - arch-tower
  tasks:
    - name: Install neovim
      become: '{{ become_for_package }}'
      ansible.builtin.package:
        name:
          - neovim
          - cmake
          - ripgrep
          - bash-language-server
          - lua-language-server
          - elixir-ls
          - tailwindcss-language-server
        state: latest
    - name: Create neovim config dir
      ansible.builtin.file:
        dest: "{{ user_home }}/.config/nvim"
        state: directory
    - name: Install neovim config
      ansible.builtin.file:
        src: "{{ config_home }}/home/.config/nvim/{{ item }}"
        dest: "{{ user_home }}/.config/nvim/{{ item }}"
        state: link
      loop:
        - "init.lua"
        - "lua"
