#!/bin/ansible-playbook

- hosts:
    - arch-tower
  become: yes
  tasks:
    - name: Install kitty
      ansible.builtin.package:
        name:
          - kitty
        state: latest
    - name: Install kitty config
      ansible.builtin.file:
        src: "{{ config_home }}/home/.config/kitty/kitty.conf"
        path: "{{ user_home }}/.config/kitty/kitty.conf"
        state: link
