#!/bin/ansible-playbook

- hosts:
    - arch-tower
  vars:
    fonts_path: "{{ user_home }}/.local/share/fonts/ttf"
  tasks:
    - name: Install kitty
      ansible.builtin.package:
        name:
          - kitty
        state: latest
    - name: Install kitty config
      ansible.builtin.file:
        src: "{{ config_home }}/home/.config/kitty/kitty.conf"
        dest: "{{ user_home }}/.config/kitty/kitty.conf"
        state: link
