#!/bin/ansible-playbook

- hosts:
    - current
  vars:
    fonts_path: "{{ user_home }}/.local/share/fonts"
  tasks:
    - name: Install unzip
      become: '{{ become_for_package }}'
      ansible.builtin.package:
        name:
          - unzip
        state: latest
    - name: Create temporary directory for download fonts
      ansible.builtin.file:
        path: "{{ user_home }}/tmp/NerdFont"
        state: directory
    - name: Download NerdFont
      ansible.builtin.get_url:
        url: "https://github.com/ryanoasis/nerd-fonts/releases/download/v3.0.1/AnonymousPro.zip"
        dest: "{{ user_home }}/tmp/NerdFont/NerdFont.zip"
      register: nerdfont_zip
    - name: Unarchive NerdFont.zip
      ansible.builtin.unarchive:
        remote_src: true
        src: "{{ nerdfont_zip.dest }}"
        dest: "{{ user_home }}/tmp/NerdFont"
    - name: Create ttf folder for fonts
      ansible.builtin.file:
        path: "{{ fonts_path }}/ttf"
        state: directory
    - name: Get NerdFont files
      ansible.builtin.find:
        path: "{{ user_home }}/tmp/NerdFont"
        patterns: "*.ttf"
      register: find
    - name: Install NerdFont
      ansible.builtin.copy:
        remote_src: true
        src: "{{ item.path }}"
        dest: "{{ fonts_path }}/ttf/"
      loop: "{{ find.files }}"
    - name: Cleanup NerdFont
      ansible.builtin.file:
        path: "{{ user_home }}/tmp"
        state: "absent"
