#! /bin/sh

sxhkd &

bspc monitor --reset-desktops I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a firefox desktop='^9'
bspc rule -a keepassxc desktop='^0'

feh --bg-fill "$HOME/wallpapers/forest.jpg" &
